import { api } from './api';

export const riderAPI = {
  getProfile:          () => api.get('/rider/profile'),
  updateProfile:       (data: object) => api.patch('/rider/profile', data),
  addPhone:            (phoneNumber: string) => api.post('/rider/phones', { phoneNumber }),
  removePhone:         (phone: string) => api.delete(`/rider/phones/${phone}`),
  getLocations:        (city?: string) => api.get('/rider/locations', { params: { city } }),
  getAvailableDrivers: (city?: string) => api.get('/rider/drivers/available', { params: { city } }),
  getVehicles:         (type?: string) => api.get('/rider/vehicles', { params: { type } }),
  requestRide:         (data: object) => api.post('/rider/rides', data),
  getRideHistory:      (status?: string) => api.get('/rider/rides', { params: { status } }),
  getRideDetail:       (id: number) => api.get(`/rider/rides/${id}`),
  cancelRide:          (id: number, reason?: string) => api.patch(`/rider/rides/${id}/cancel`, { reason }),
  applyPromo:          (id: number, code: string) => api.post(`/rider/rides/${id}/promo`, { code }),
  makePayment:         (data: object) => api.post('/rider/payments', data),
  getPayments:         () => api.get('/rider/payments'),
  getActivePromos:     () => api.get('/rider/promocodes'),
  getMyPromos:         () => api.get('/rider/my-promocodes'),
  rateRide:           (id: number, data: object) => api.post(`/rider/rides/${id}/rate`, data),
  rateDriver:         (data: object) => api.post('/rider/driver/rate', data),
  fileComplaint:       (data: object) => api.post('/rider/complaints', data),
  getComplaints:       () => api.get('/rider/complaints'),
  getSavedLocations:   () => api.get('/rider/saved-locations'),
  addSavedLocation:    (data: object) => api.post('/rider/saved-locations', data),
  updateSavedLocation: (id: number, data: object) => api.patch(`/rider/saved-locations/${id}`, data),
  deleteSavedLocation: (id: number) => api.delete(`/rider/saved-locations/${id}`),
  // Safety Features
  triggerSOS:          (data: object) => api.post('/rider/sos', data),
  shareTrip:           (data: object) => api.post('/rider/share-trip', data),
  getEmergencyContacts: () => api.get('/rider/emergency-contacts'),
  addEmergencyContact: (data: object) => api.post('/rider/emergency-contacts', data),
  deleteEmergencyContact: (id: number) => api.delete(`/rider/emergency-contacts/${id}`),
  // Notifications
  getNotifications:     (unreadOnly?: boolean) => api.get('/rider/notifications', { params: { unreadOnly } }),
  markNotificationsRead: (ids: number[]) => api.post('/rider/notifications/mark-read', { notificationIds: ids }),
  markAllNotificationsRead: () => api.post('/rider/notifications/mark-all-read'),
  deleteNotification:   (id: number) => api.delete(`/rider/notifications/${id}`),
  getSafetyAlerts:      () => api.get('/rider/notifications/safety-alerts'),
  resolveSafetyAlert:   (id: number) => api.post(`/rider/notifications/safety-alerts/${id}/resolve`),
};
